apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: spring-28624 
  janus-idp.io/tekton: spring-28624
  backstage.io/kubernetes-id: spring-28624
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: spring-28624
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  