apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: spring-28624
  janus-idp.io/tekton: spring-28624
  backstage.io/kubernetes-id: spring-28624
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: spring-28624
resources:
- deployment.yaml
- route.yaml
- service.yaml
